# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 523bfc177b76395df0d8c860a9b3026961af4dcd849ff12cbef64b0f67cbf447b4eee736f9d6620b2dc540622647a85058662b15ec6519bd8d2534ded362eacc

test:
  secret_key_base: 23d082cd64518395a8055d451a147ccf27937afeb80a3105c721ea776b85e0daa7f2a15efd194d681c24355255054a651f816c8850b03b1101f5d2daa4207012

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
